apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.36.0 (ae2a39403)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose -f compose.yaml convert","kompose.version":"1.36.0 (ae2a39403)"},"labels":{"io.kompose.service":"pihole"},"name":"pihole","namespace":"pihole-ns"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"pihole"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose -f compose.yaml convert","kompose.version":"1.36.0 (ae2a39403)"},"labels":{"io.kompose.service":"pihole"}},"spec":{"containers":[{"env":[{"name":"FTLCONF_dns_listeningMode","value":"all"},{"name":"FTLCONF_webserver_api_password","value":"correct horse battery staple"},{"name":"TZ","value":"Europe/London"}],"image":"pihole/pihole:latest","name":"pihole","ports":[{"containerPort":53,"protocol":"TCP"},{"containerPort":53,"protocol":"UDP"},{"containerPort":80,"protocol":"TCP"},{"containerPort":443,"protocol":"TCP"}],"securityContext":{"capabilities":{"add":["SYS_NICE"]}},"volumeMounts":[{"mountPath":"/etc/pihole","name":"pihole-data-claim"}]}],"restartPolicy":"Always","volumes":[{"name":"pihole-data-claim","persistentVolumeClaim":{"claimName":"pihole-data-claim"}}]}}}}
  creationTimestamp: "2025-06-24T21:07:40Z"
  generation: 2
  labels:
    io.kompose.service: pihole
  name: pihole
  namespace: pihole-ns
  resourceVersion: "173804"
  uid: 55729c71-b804-444c-9ea2-1f8e9749d60f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.yaml convert
        kompose.version: 1.36.0 (ae2a39403)
        kubectl.kubernetes.io/restartedAt: "2025-06-28T21:40:33+01:00"
      creationTimestamp: null
      labels:
        io.kompose.service: pihole
    spec:
      containers:
      - env:
        - name: FTLCONF_dns_listeningMode
          value: all
        - name: FTLCONF_webserver_api_password
          value: correct horse battery staple
        - name: TZ
          value: Europe/London
        image: pihole/pihole:latest
        imagePullPolicy: Always
        name: pihole
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_NICE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-data-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pihole-data-claim
        persistentVolumeClaim:
          claimName: pihole-data-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-28T20:40:35Z"
    lastUpdateTime: "2025-06-28T20:40:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-06-24T21:07:40Z"
    lastUpdateTime: "2025-06-28T20:40:35Z"
    message: ReplicaSet "pihole-d885b78d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
