- name: Install k3s control-plane 
  hosts: node-01 
  become: yes
  tasks:
    - name: Install k3s server 
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_TOKEN=talentedripley sh -s - 
- name: Install k3s agent
  hosts: node-02
  become: yes
  tasks:
    - name: Install k3s worker
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_URL=https://192.168.1.88:6443 K3S_TOKEN=talentedripley sh -s - # agent is assumed because of K3S_URL
