# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: jellyfin 
  namespace: jellyfin-ns 
spec:
  selector:
    app: jellyfin 
  type: LoadBalancer 
  ports:
  - name: "8096"
    port: 8096 
    protocol: TCP
    targetPort: 8096
---


